[package]
name = "scurvy"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "mac"
path = "src/bin/mac.rs"

[[bin]]
name = "ip"
path = "src/bin/ip.rs"

[dependencies]
get_if_addrs = "0.5.3"
network-interface = "1.1.1"
pnet = "0.34.0"
